language: bash

sudo: required

services:
- docker

env:
  global:
    - secure: "FmkqwkHuIDRJgRp/mG5V4irZ+zzd5nX9MpBGrTruqmn8wq5w5R5YvaUjgRRIMt8I8852K0SzjE+IYbFpFAdvmXEqbWxN8z0oscBHfcQzkbS2UkJggklec6f1Pi8AK/DRAJLDy0NYVKBbT9qAcFhROXZB/msd+6uVz1fRPcEWqaz2GQ/4CNHjp3tPc5G81cKgJTT4HF+eYf4TpQYgiRewgibjGN0De8jo2NiwLlVhGtIC2s2TqoPC/LIUP2CkbH4iBPdRsu7OmFo4FehwemTiUnJMZLsVjdQSbOXnnNr8V9YGSIGDagmlXbObiZfz7A9WOQGk5EyJocG8LYCpaHpquil7INTdqIutHvia2Iilid3RU/C0MB0Ouw/g0hvFZqyj7yTvZpsQ2qogt+E4daPD7pZTs5GHO3MQjMtKAjIEu87gKsRQvps/aJPp8y8yKprFW4uRKh4Fjqw/i+AwE8TuqUbyUtFie/MGCJLPfnLtAlkyZxqr+UCCfrkIb31Cra5WNwIr/XyOoRnzATb8zSaO90P23U4fmreYkKK8CrS9S3n2dlDWxGErRTIwe1gcXAz14hrwSlFng8HkVh40wJ5/wdnGTShU01ptFgb/EBspmBikStFjqWa8oXcGDalV8pdyWbrGXvvMjOa459KAIthrjE48B4H9iWHYrFpwt7vNaQ8="
    - secure: "RhInDjYz8ZlDk8603U5kUEZENaBLywtzFG47KmNev/Jbio0DK8f/yllooRfIOhED9nJDMBQBksd4p2qfR6VqiXNrN37SCpNwD2PzpgAcEUYIU6izwJYwzMkO5WVcSG4PDr73KaipQkjrfLq4bqWULgIdN3rp56LrhzZjrnz3Dnq2neIubN7MisTh9xflICUZcsF4umGxtqyGwdVQf1mhruhsdaF3BIMavi9ZZfr8m5gt9h9j+RZ/CVLEnAtSpn6TgNNhN8IMpNM1v/qEWXxoBRDKyvTsAMj0hEJCb3OCYoHh+4D25ZXefms9/uHdZFguk4b2QTAkhi8QxBuMmT8T/0fDy3RX1YpPiK0kIQi33FC2wgvN290LVhtXHq+7V8+xmlEM1W0oW+YWIiM1xn+XmwDpFW/rrbrL5MmJlQgXNb5u975AVqFo+Z+lkt1ukxcVC6Cv4gmJlW+NcmrUAhQXDC3xKhvDKaZCE/lfxKouHCk40tONQOiuxs12YIM4qj8/x3iS0A4hkB6jGOc5sKxqci56Qe50pFgumBC+ViSVsjNi7yeEqr15eXb29dFxZn8mA8pafLnOqcRO/71peLJHnfIywkb0OHjU71wgN6no5npNRbW4ujBsthOnlnHRbutqOY52n9Dcf1BZ7r1vJTN+JKfea3K1ao8lhVwZS13eTuw="
    - secure: "PCaCK7XWAGZuhPpPegSy3pRVLUPEW7HB1+xPKiVgje7UVh9Qq7O/Y8C3nM7506I6oXkLBKiIaVRIthoQru/nmxlCUS1vJjsj4vC+GhF8b/GP9CYPH3KzB1Jvcy5ln8vgVA/PDZt87qoflquKNNhaTo72ChQivF9kVJFjluiHK7zd16+ob2R/evwB9GbjAe2/sx+JzBaLKfsspJrGxQiHmLbFB1+/HWsJZEL+G1IhOb59IgJA9BRuMsC77PXN7scoDTuRcG5bKz19ZpzT27fcWrmElyp8Bb0HUURAr0j1sVuKEjWk7iyv3NskT+e4coAnQvuLKq5KPVeKx7/0QLyLPNsa12XjzAl5ZrnWxVaxyI0bRxE5ArLJU3yP3rEJt/g/BsIVF0YSMSxNwcB8gXdXrspnk2vkE42SEZXC+WwIIIg5tIxHif87xGfWfDMc83dosS+cB5KEF28r+0BCKSnLy2+Df3eiBdRS65Z4KwbKCygGdTrytQD+LadBvlXgpkLpsblfIt2kyDZoE2ZaBgWEaXKmMxD68leqgic3DGwJVecr0zFLDF/MtVliI3pqxelI3We9Zejul5S6fA0/RQwDKjwVcbn0T7tvGyXleJa/3jAzhMWcmX5MuSQMVJcCJEAKKPl6UBRpliRSTT4THuuaOCMJCoiMKF4h/F05QEQDPto="
    - PROJECT="php"
    - REPOSITORY="encodeering"
    - BRANCH="$TRAVIS_BRANCH"
    - COMMIT="287a157544a8e43032ecb2879ff778d10c0d0e37"
  matrix:
    - ARCH=amd64 VERSION=5.6 VARIANT=apache
    - ARCH=amd64 VERSION=7.0 VARIANT=apache

install:
- bash <(curl https://raw.githubusercontent.com/encodeering/docker-ci/master/install.sh) 0.1.4

before_script:
- sudo -E bash ./module.sh "." "./setup.sh" "https://github.com/docker-library/php.git" "modules/$PROJECT" "$COMMIT"

script:
- sudo -E bash ./module.sh "modules" "./build.sh"

after_script:
- docker images

deploy:
  script: sudo -E bash ./module.sh "." "./release.sh"
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
