diff --git a/5.6/apache/Dockerfile b/5.6/apache/Dockerfile
index 24bd251..6c5ecc0 100644
--- a/5.6/apache/Dockerfile
+++ b/5.6/apache/Dockerfile
@@ -46,8 +46,7 @@ ENV PHP_VERSION 5.6.21
 ENV PHP_FILENAME php-5.6.21.tar.xz
 ENV PHP_SHA256 566ff1a486cb0485ed477a91ea292423f77a58671270ff73b74e67e3ce7084f9
 
-RUN set -xe \
-	&& buildDeps=" \
+ENV buildDeps=" \
 		$PHP_EXTRA_BUILD_DEPS \
 		libcurl4-openssl-dev \
 		libedit-dev \
@@ -55,7 +54,8 @@ RUN set -xe \
 		libssl-dev \
 		libxml2-dev \
 		xz-utils \
-	" \
+	"
+RUN set -xe \
 	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
 	&& curl -fSL "http://php.net/get/$PHP_FILENAME/from/this/mirror" -o "$PHP_FILENAME" \
 	&& echo "$PHP_SHA256 *$PHP_FILENAME" | sha256sum -c - \
@@ -82,12 +82,13 @@ RUN set -xe \
 		--with-curl \
 		--with-libedit \
 		--with-openssl \
-		--with-zlib \
-	&& make -j"$(nproc)" \
+		--with-zlib
+ONBUILD RUN cd /usr/src/php && make -j"$(nproc)" \
 	&& make install \
 	&& { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } \
 	&& make clean \
-	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps
+	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps \
+	&& unset buildDeps
 
 COPY docker-php-ext-* /usr/local/bin/
 
